### ISSUE TITLE
Issue112 - Adjust Scores Tally so Multiplayer Maps functions properly

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#112]
Currently, PEWI score calculations are wildly inaccurate ("scores" (0-100 values), NOT raw score calculations (mg, tons/acre)) when the map is cut up into multiplayer sections and a single section loaded. Need to fix this. 

Will likely involve:
- Rewriting Points/Percentage calculation in Results pages to scale with size of watershed. Must be done for each calculation.
- Updating Results graphics to reflect these changes.

See attachment for more details and screenshots.
[2017_Update_112_Scores Rebasing Due to Multiplayer.docx](https://github.com/LESEM-PEWI/pewi3.0/files/1011926/2017_Update_112_Scores.Rebasing.Due.to.Multiplayer.docx)

**Comment by elizabethli1998** [comment]
I will look into this

**Comment by Xemnaes** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
The issue was that the multiplayer maps were treating the tiles not allocated to the player as still existing on the map. Simply removing their values and treating them as null (NA) renders this result (using about the same setup from your word document).

 
![image](https://user-images.githubusercontent.com/26779242/27350219-603a4cca-55bf-11e7-81fd-12c5dbf7aeec.png)


![image](https://user-images.githubusercontent.com/26779242/27350231-6987bab0-55bf-11e7-9c97-7bf907f98651.png)

![image](https://user-images.githubusercontent.com/26779242/27350286-8bbc873c-55bf-11e7-8635-fb00cb79e25e.png)

![image](https://user-images.githubusercontent.com/26779242/27350312-99afdf6a-55bf-11e7-8361-48da5500dc47.png)

@tomtinkerer
