### ISSUE TITLE
Issue230 - Bug: Set up multiplayer, remove player function

### ISSUE THREAD

**Issue by qaws01395** [LESEM-PEWI/pewi3.0#230]
If you do the following step, you can find this bug.
1. Add to more than 3 players
2. Select the second player ( any player whose number smaller than the biggest one )
3. Click remove player

Then the player isn't removed (which I think it's correct), but his land got removed.

The other one:
1. Place first player's land
2. Place second player's land and overlap it on the first player's
3. remove the second player
Then the land where the two player intersect get removed too. 
![image](https://user-images.githubusercontent.com/7816231/28281181-e74a37c0-6aeb-11e7-94d6-186254239913.png)
![image](https://user-images.githubusercontent.com/7816231/28281205-f65b367e-6aeb-11e7-8a46-d665b7f9805a.png)
![image](https://user-images.githubusercontent.com/7816231/28281234-09c6987a-6aec-11e7-8540-315576417bd6.png)

**Comment by Xemnaes** [comment]
Both problems are intentional by design. 

Say a given multiplayer map has 4 players. If each player has land allocated, and the user wants to delete player 2, their land is reabsorbed by the first player and the player count is reduced by 1. This cascades all of the land divisions down by one player as well, which is why they change color.

As for the second issue, when a player overlaps another, they are essential overwriting their land. If their land is deleted, it is reabsorbed into player 1. If the user wishes to retain the two players land uses as one, they can use the merge function.

**Comment by qaws01395** [comment]
Clarified by Alex.
