### ISSUE TITLE
Issue #299 - Restricting Options Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#299]
1. Randomize PEWI, with a giant block of Mixed F&V in the middle
2. Go to options, turn off corn and soybean conv and cons
3. Return to map

ERROR: This process does properly restrict the eliminated landuses, but is NOT supposed to randomize the whole map before doing so. NOTE: When done with the fix, please test to ensure it is properly applied to all years loaded (1,2,3)

BEFORE:
![image](https://user-images.githubusercontent.com/11810901/29182786-c0f87c8e-7dc5-11e7-8b74-c6eb86591208.png)

AFTER:
![image](https://user-images.githubusercontent.com/11810901/29182798-cee9bd62-7dc5-11e7-8605-7fc3341ca604.png)

**Comment by tomtinkerer** [comment]
Alex, this one is for you

**Comment by Xemnaes** [comment]
Currently, the restrictions work by randomizing each map with the allowed list of land use types.

The fix will work as follows:

- If a given land use for a tile for a year is **restricted**, change that tile's land use type to the new default land use type.
- If a given land use for a tile for a year is **not restricted**, do not modify the land use type.

If a user randomizes a map, then restricts some land uses, the newly generated map will contain a lot of the new default land use type. If the user wishes to generate a new random map with more randomness, they can then do so.

**Comment by Xemnaes** [comment]
The issue is fixed, with the following example.

Randomized map (with unrestricted land uses as a grid over each)

![image](https://user-images.githubusercontent.com/26779242/29187544-bf2a82ac-7dd5-11e7-9d78-9e17298c660d.png)
![image](https://user-images.githubusercontent.com/26779242/29187564-d3c97ba0-7dd5-11e7-8ca0-66d1ebe1e4a0.png)
![image](https://user-images.githubusercontent.com/26779242/29187583-e55417b8-7dd5-11e7-87e0-777985cab4c9.png)

Then, land uses are restricted in options:
![image](https://user-images.githubusercontent.com/26779242/29187606-f93c1b22-7dd5-11e7-92f3-03f4d85e1f56.png)

The result:
![image](https://user-images.githubusercontent.com/26779242/29187621-0948a936-7dd6-11e7-8a1a-52da9b623e82.png)
![image](https://user-images.githubusercontent.com/26779242/29187629-124a61fa-7dd6-11e7-85fa-b558869f92ee.png)
![image](https://user-images.githubusercontent.com/26779242/29187637-1b809e1a-7dd6-11e7-9108-656ea9a5a80c.png)

**Comment by Xemnaes** [comment]
Pull request submitted.
