### ISSUE TITLE
Issue #304 - Multiplayer Division Available Players Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#304]
- Open Multiplayer Division, assign pieces of land to 6 players
- Go to Main Menu
- Open Multiplayer Division again
![image](https://user-images.githubusercontent.com/11810901/29183265-a05b3d8e-7dc7-11e7-8784-cfeebbe61ceb.png)

ERROR: Ownership is currently all under Player 1 (the default), but previously added Players 2-6 are already added in the toolbar area.

**Comment by Xemnaes** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
**UPDATE:** It seems that the method which resets multiplayer mode is only called when entering a different PEWI mode, rather than when exiting from multiplayer mode. For example:

- Open multiplayer mode and assign 6 players
- Go to the main menu and enter sandbox mode
- Go to the main menu and enter multiplayer mode

The players are now reset. The fix will involve calling this method (or at least the player resetting method) once the user leaves multiplayer mode, not when they enter a different mode.

**Comment by Xemnaes** [comment]
Pull request submitted.
