### ISSUE TITLE
Issue #341

### ISSUE THREAD

**Issue by qaws01395** [LESEM-PEWI/pewi3.0#343]
Today I wanted to a little bit show off to friends the website. But when I clicked on the printer icon, the CSS looks awfully broken, then my heart's broken too 
![image](https://user-images.githubusercontent.com/7816231/30044274-cf69ce7a-91c1-11e7-80cb-82bb993994f1.png)
![image](https://user-images.githubusercontent.com/7816231/30044282-d4845e16-91c1-11e7-95ce-8ff9a7f14fc1.png)
![image](https://user-images.githubusercontent.com/7816231/30044288-da422766-91c1-11e7-96ea-ac9d7c9a1e24.png)

I think might be the position value of css was changed or something

**Comment by Xemnaes** [comment]
So when I went to recreate this on my master branch, I could not reproduce the bug...

However, since this appears to be a CSS issue, I tried deleting _style_printOptions.css_ in the _htmlFrames_ folder. Doing so, I was able to reproduce this exact same styling error.

I'm guessing that when the files were uploaded to the nrem website, _style_printOptions.css_ was not included.

**Comment by tomtinkerer** [comment]
@Xemnaes Please retest on multiple hardware configurations. The problem is with client-side compatibility, not server side. Below is an image of me testing (left) a local copy of the code and (right) what is currently on the website.

![image](https://user-images.githubusercontent.com/11810901/30364737-0ef3ca2c-982b-11e7-88ca-c8a7bf70e1af.png)

Tested in both Firefox and Chrome, no problems on my work machine. Will test on personal computers at home when I get a chance, but it was throwing this error previously.
