### ISSUE TITLE
Issue500 - Save/Load Map Customize Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#500]
Open PEWI, make some land use changes. Go into Customize, and turn several land use options off.  Lock the Precipitation levels. Save & Exit, then download the save file for your session. Close the browser.

Restart the browser. Open PEWI, go Sandbox, and upload your save file. You'll notice the land use restrictions and precipitation locks transferred in. 

Now navigate to the Customize page. You'll see that no Customize settings transferred to this page - as a result, simply hitting Save & Exit will remove all of the settings previously established. Even the user never navigates here, but instead makes changes and then saves their file, the new file will not include these restrictions. 

Fixing this issue should involve setting the Customize page to include uploaded settings.

**Comment by HameisterEric** [comment]
This bug is more wide spread than precipitation levels, what needs to happen is that on load all settings need to be taken into effect. So they need to affect the board as if save and exit were just pressed, and also affect the optionsString so that on resave or opening settings again it will be the same.

**Comment by tomtinkerer** [comment]
@HameisterEric what's the status of this issue?

**Comment by HameisterEric** [comment]
This problem was only partially addressed by another issue, I will look into finishing this issue.
