### ISSUE TITLE
Issue554 - Hotkeys have gone whack

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#554]
Hotkeys are not functioning appropriately. Test them - example include "Q" activating print instead of flyover, arrow keys not working, etc. Fix these back to their original settings.

**Comment by jbweiland** [comment]
The hot keys are messed up because multiple additions were made at the same time. This means both people added their new keys to the same spot in the hotkeyArr which obviously causes issues. To fix this the hotkeyArr needs to simply be reorganized so that all instances of it are the same throughout the code.

**Comment by jbweiland** [comment]
Jared is working on this.
