### ISSUE TITLE
Issue650- Accounting for years in costs

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#650]
Currently the costs for mapData do not consider multi-year costs. The agreed upon solution was to make an parallel array for all multiyear costs to divide by.

**Comment by HameisterEric** [comment]
I am on it

**Comment by tomtinkerer** [comment]
When reading in the Econ data, the following scales/multipliers need to be considered:

Each land use lasts for a different period of time. (I.e. corn/soy 1 year, strawberries 3, grapes 22). Divide each line item by the appropriate number of years.
Mixed Fruits & Vegetables line items need to all be divided by 4 (because this land use is evening split between the four crops)
